# Ubuntu 이미지를 가져옵니다.
FROM ubuntu:20.04

# Node.js 설치
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# 애플리케이션 디렉터리를 만듭니다
WORKDIR /usr/src/app

# 애플리케이션 의존성을 설치합니다
# package.json과 package-lock.json을 복사합니다
COPY package*.json ./

RUN npm install
# 프로덕션을 위한 코드를 빌드하려면 아래 코드를 사용하십시오:
# RUN npm ci --only=production

# 애플리케이션 소스를 이 이미지로 복사합니다
COPY . .

# 애플리케이션을 실행하는 데 필요한 포트를 열어줍니다
EXPOSE 3000

# 애플리케이션을 실행합니다
CMD [ "npm", "start" ]
